language: python
python:
- '3.5'
install: pip install .
script: python setup.py test
deploy:
  provider: pypi
  user: weargoggles
  password:
    secure: Sqol6bnHqAEjSuy3sRgwXpU0uQh7SvfOjeGQslVO2lV2OkfACnGiOGdfg1aS+QC32wPX0SSw6pRdqn0cMd8vWGAY3FeOuFVYpFy2imEcsPTCw5FqlDZUmmcr483UQO1nHZi6cmWirZu5R1SSvdQIjlfzmoOXtXURVqzmhBWFU+Q=
  on:
    tags: true
    all_branches: true
