language: python
python:
- '3.5'
install: pip install .
script: python setup.py test
deploy:
  provider: pypi
  user: weargoggles
  password:
    secure: DOH2GQCrBpr6EHm7OhJdiJ0nqJNQobvN+i/W7uyjCH8kzdJnTqkJamcRZjMjq3pH4hiijrw2dHi0S2MlDRy8uAXozKw/rBxdHFOzUvIcNsMDwCCOYexYYnS9HORRjA7eJeXtHCZVHWurjsx7sz/rLc2VdJz3Oh3urUkQkeqvzkfMgTF2kpHTbmKfRmVUGW8ukmGQTcnrrSfdpfIsC9ywUto/KYI51uLNSFdLbn8B58UIhhqCQfAS/AWNCEP+voXFrKbixl2eFDBUXikgssKqMrYEP2e9kG8Vw+7zCUdPtbfMr7CAfc1cnMWjPlocoCEpincanPwrcI/AmOn2PR9HHAzcgC5h6iOdCr0mCgdnNnLh5wRGTI1qZsBU0MCbjnQRYABc73m8mZ8IJcXMb33oL8OHQG9199JQA0QDligVChK44aMYdYlAJNoE1f+0jdAhPFMY4Qfeb8GWje0RyD/JklIrdjpdPSxEpr/zwBwTkFXVGiWpXPtoOgOh3Sys533d7CnZs2mobV8J6IqafRefA4cd2ZY2hSDVjwW4sCdUfHIfsicerp67XGMTlWcDBnvpW4RlrKu22aXGaIqms2FKNH7LTK0EmGG8syHEwidpIm2um1i1Xg+RqydMoMAOl0cLmrl3qJUMAoH16G2p9u8cQpjftbtgaSw4YWz2cT2KNCo=
  on:
    tags: true
    all_branches: true
